name: Release PAPI

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version like 7.2.0.0"
        required: true
      start_commit:
        description: "Starting commit (non-inclusive) for changelog (or 'LAST_TAG')"
        required: true
      tag_name:
        description: "Tag to create on this commit when dispatching manually (e.g. papi-7-2-0-t)"
        required: true
  push:
    tags:
      - "papi-*"

permissions:
  contents: write # needed to create releases & push tags (with GITHUB_TOKEN)

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz autoconf make tar gzip

      # If manual dispatch, create the tag here so downstream steps can use it
      - name: Create tag on workflow_dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag -a "${{ inputs.tag_name }}" -m "Release ${{ inputs.version }}"
          git push origin "${{ inputs.tag_name }}"

      - name: Compute TAG_NAME
        id: tag
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            echo "tag_name=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          else
            echo "tag_name=${{ inputs.tag_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Bump versions in repo files
        run: |
          python3 scripts/release.py bump --version "${{ inputs.version || 'auto' }}"

      - name: Build manpages
        run: |
          make -C doc
          make -C doc install

      - name: Generate changelog
        run: |
          python3 scripts/release.py changelog \
            --from "${{ inputs.start_commit || 'LAST_TAG' }}" \
            --out CHANGELOG.md

      - name: Build tarball
        run: |
          python3 scripts/release.py package --name "papi-${{ inputs.version }}"
          sha256sum *.tar.gz > SHA256SUMS

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag_name }}
          name: "PAPI ${{ inputs.version || steps.tag.outputs.tag_name }}"
          body_path: CHANGELOG.md
          files: |
            *.tar.gz
            SHA256SUMS

      # Optional: Deploy docs to the server (set SSH secrets in repo settings)
      # - name: Deploy docs
      #   uses: appleboy/scp-action@v0.1.7
      #   with:
      #     host: ${{ secrets.DOCS_HOST }}
      #     username: ${{ secrets.DOCS_USER }}
      #     key: ${{ secrets.DOCS_SSH_KEY }}
      #     source: "doc/html/*"
      #     target: "/path/to/websites/icl.utk.edu/projectsdev/papi/docs"
